name: anymex
description: "EchoSphere - Smart AI-Powered College Announcement Management System"
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.4.4 <4.0.0"
    flutter: ">=3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # Core State, Networking & Backend
    get: ^4.7.3
    provider: ^6.1.2
    http: ^1.2.2
    dio: ^5.8.0+1
    supabase_flutter: ^2.8.0
    firebase_core: ^4.4.0
    firebase_analytics: ^12.1.1
    flutter_dotenv: ^5.2.1

    # UI Design System, Fonts & Icons
    google_fonts: ^6.2.1
    hugeicons: ^0.0.7
    flutter_iconly: any
    flutter_svg: ^2.0.10
    cached_network_image: ^3.4.1
    shimmer: ^3.0.0
    blur: ^4.0.0
    checkmark: ^0.0.2+1
    dynamic_color: ^1.7.0
    auto_size_text: ^3.0.0
    marquee: ^2.3.0
    super_sliver_list: ^0.4.1
    flutter_markdown: ^0.7.6
    markdown: ^7.3.0

    # System, Device, File & Utilities
    shared_preferences: ^2.5.2
    intl: ^0.20.1
    path: ^1.9.0
    path_provider: any
    permission_handler: ^11.3.1
    file_picker: ^8.1.7
    device_info_plus: ^11.2.2
    package_info_plus: any
    share_plus: ^11.0.0
    url_launcher: any
    flutter_inappwebview: ^6.1.5
    image: any
    palette_generator: ^0.3.3+7
    cross_platform_video_thumbnails: ^0.1.0
    crypto: any

    # Desktop Windows Utilities
    window_manager: ^0.4.3
    win32: any
    ffi: any

dev_dependencies:
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.14.2
    inno_bundle: ^0.7.4

flutter_launcher_icons:
    android: false
    ios: false
    image_path: "assets/images/logo.png"
    windows:
        generate: true
        image_path: "assets/images/logo.png"
        icon_size: 256
    macos:
        generate: false
        image_path: "assets/images/logo.png"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - .env

    fonts:
        - family: Poppins
          fonts:
              - asset: assets/fonts/Poppins/Poppins-Regular.ttf

        - family: Poppins-SemiBold
          fonts:
              - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

        - family: Poppins-Bold
          fonts:
              - asset: assets/fonts/Poppins/Poppins-Bold.ttf

inno_bundle:
    id: 8fbd47cb-d6e1-5343-a9f6-61661647c94c
    publisher: EchoSphere
    name: EchoSphere
    version: 1.0.0
    admin: auto
    installer_icon: ./windows/runner/resources/app_icon.ico
