; PlatformIO Project Configuration File
; Project: EchoSphere ESP32 Smart Speaker & Live Notice Display Node
; Board: Classic 38-Pin ESP32 NodeMCU DevKit (esp32dev)
; Peripherals: MAX98357A I2S 3W Amplifier, 8Ω Speaker, 1.8" Color TFT ST7735 SPI

[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.4
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit GFX Library @ ^1.11.9
    schreibfaul1/ESP32-audioI2S @ 3.0.12
