org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
kotlin.incremental=true
kotlin.caching.enabled=true
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
android.builtInKotlin=false
android.newDsl=false


